# Generated by Django 5.2.1 on 2025-05-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'verbose_name': 'Event registration', 'verbose_name_plural': 'Event registrations'},
        ),
    ]
